import type { User, Session } from 'better-auth/minimal';
import { createAuth } from '$lib/server/auth';

// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
	// Secrets not generated by `wrangler types` (they're in .dev.vars only)
	interface Env {
		VAPID_PUBLIC_KEY: string;
		VAPID_CONTACT: string;
		VAPID_PRIVATE_KEY: string;
	}

	namespace App {
		interface Platform {
			env: Env;
			ctx: ExecutionContext;
			caches: CacheStorage;
			cf?: IncomingRequestCfProperties;
		}

		interface Locals {
			user?: User;
			session?: Session;
			auth: ReturnType<typeof createAuth>;
			phoneVerified: boolean;
		}

		// interface Error {}
		// interface PageData {}
		// interface PageState {}
	}
}

export {};
