import type { User, Session } from 'better-auth/minimal';
import { createAuth } from '$lib/server/auth';

// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
	// Secrets not generated by `wrangler types` (they're in .dev.vars only)
	interface Env {
		/** Legacy Resend credential; used when EMAIL_PROVIDER is omitted. */
		RESEND_API_KEY?: string;
		/** Cloudflare Images API account and public-delivery hash for this instance. */
		CF_IMAGES_ACCOUNT_ID: string;
		CF_IMAGES_ACCOUNT_HASH: string;
		/** Server-only key for fetching the private full-frame image variant. */
		CF_IMAGES_SIGNING_KEY?: string;
		/** DBBL's operator-configured API origin. */
		DBBL_API_URL: string;
		VAPID_PUBLIC_KEY: string;
		VAPID_CONTACT: string;
		VAPID_PRIVATE_KEY: string;
		EMAIL_FROM?: string;
		/** `resend` or `ses`. Omit only when using the legacy Resend configuration. */
		EMAIL_PROVIDER?: 'resend' | 'ses';
		REKOGNITION_ACCESS_KEY_ID?: string;
		REKOGNITION_SECRET_ACCESS_KEY?: string;
		REKOGNITION_REGION?: string;
		REKOGNITION_SESSION_TOKEN?: string;
		SES_ACCESS_KEY_ID?: string;
		SES_SECRET_ACCESS_KEY?: string;
		SES_REGION?: string;
		SES_SESSION_TOKEN?: string;
		DBBL_ENABLED?: string;
		INSTANCE_THEME?: string;
		INSTANCE_NAME?: string;
		INSTANCE_TAGLINE?: string;
		INSTANCE_URL?: string;
		INSTANCE_LEGAL_EMAIL?: string;
		INSTANCE_SOURCE_URL?: string;
		/** Set to true to show the public beta landing page instead of the app. */
		INSTANCE_PRELAUNCH_MODE?: string;
		/** Comma-separated test account emails allowed through the prelaunch gate, without admin access. */
		INSTANCE_PRELAUNCH_TESTER_EMAILS?: string;
	}

	namespace App {
		interface Platform {
			env: Env;
			ctx: ExecutionContext;
			caches: CacheStorage;
			cf?: IncomingRequestCfProperties;
		}

		interface Locals {
			user?: User;
			session?: Session;
			auth: ReturnType<typeof createAuth>;
			phoneVerified: boolean;
		}

		// interface Error {}
		// interface PageData {}
		// interface PageState {}
	}
}

export {};
